language: node_js

node_js:
  - stable

install:
  - npm install

jobs:
  include:
    - stage: "Test and lint"
      name: "Test"
      script: npm run test
    - name: "Lint"
      script: npm run lint:validate
